package com.cinema.ui;

import com.cinema.beanControll.Bean;
import com.cinema.beanControll.LoadFrame;
import com.cinema.dialog.QuestionDialog;
import com.cinema.helper.DateHelper;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame; 
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Nhu Huynh
 */
public class MainScreenStaff extends javax.swing.JFrame {

    DateHelper clock;
    public MainScreenStaff() {
        initComponents();
        setLocationRelativeTo(null);
        init();
        LoadFrame cf = new LoadFrame(jpnQuanLyPhim);
        cf.setView(jlbLichChieu);
        ArrayList<Bean> listItem = new ArrayList<>();
        listItem.add(new Bean("LichChieu", jlbLichChieu));
        cf.setEvent(listItem);
    }
    
    public void init(){
        this.clock = new DateHelper(jlbTime);
        this.clock.start();
        lblHinh.setIcon(new ImageIcon(new ImageIcon("src\\com\\cinema\\avatar\\A2SZ8RDM73n.png").getImage().getScaledInstance(lblHinh.getWidth(), lblHinh.getHeight(), Image.SCALE_SMOOTH)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlbClose = new javax.swing.JLabel();
        jlbExit1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jpnQuanLyPhim = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jButton1 = new javax.swing.JButton();
        jlbAvatar = new javax.swing.JPanel();
        lblHinh = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jlbTime = new javax.swing.JLabel();
        jlbLichChieu = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jlbClose.setFont(new java.awt.Font("Tahoma", 1, 57)); // NOI18N
        jlbClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbClose.setText("-");
        jlbClose.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jlbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbCloseMouseExited(evt);
            }
        });
        jPanel2.add(jlbClose);
        jlbClose.setBounds(1430, 0, 50, 50);

        jlbExit1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jlbExit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinema/image/xExit.png"))); // NOI18N
        jlbExit1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 2, new java.awt.Color(0, 0, 0)));
        jlbExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbExit1MouseExited(evt);
            }
        });
        jPanel2.add(jlbExit1);
        jlbExit1.setBounds(1480, 0, 50, 50);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinema/image/cineWorld.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 240, 50);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 50));

        jpnQuanLyPhim.setBackground(new java.awt.Color(204, 204, 204));
        jpnQuanLyPhim.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jpnQuanLyPhimLayout = new javax.swing.GroupLayout(jpnQuanLyPhim);
        jpnQuanLyPhim.setLayout(jpnQuanLyPhimLayout);
        jpnQuanLyPhimLayout.setHorizontalGroup(
            jpnQuanLyPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1286, Short.MAX_VALUE)
        );
        jpnQuanLyPhimLayout.setVerticalGroup(
            jpnQuanLyPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );

        getContentPane().add(jpnQuanLyPhim, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 1290, 770));

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        kGradientPanel1.setkEndColor(new java.awt.Color(153, 153, 153));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 102, 102));
        kGradientPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jButton1.setText("ĐĂNG XUẤT");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 102, 102)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1);
        jButton1.setBounds(0, 720, 240, 50);

        jlbAvatar.setBackground(new java.awt.Color(51, 51, 51));
        jlbAvatar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 1, 1, new java.awt.Color(0, 102, 102)));
        jlbAvatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbAvatarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jlbAvatarLayout = new javax.swing.GroupLayout(jlbAvatar);
        jlbAvatar.setLayout(jlbAvatarLayout);
        jlbAvatarLayout.setHorizontalGroup(
            jlbAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );
        jlbAvatarLayout.setVerticalGroup(
            jlbAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        kGradientPanel1.add(jlbAvatar);
        jlbAvatar.setBounds(10, 10, 70, 70);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinema/image/maNaGerIcon.png"))); // NOI18N
        jLabel13.setText("STAFF");
        kGradientPanel1.add(jLabel13);
        jLabel13.setBounds(90, 10, 100, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinema/image/position.png"))); // NOI18N
        jLabel14.setText("STAFF");
        kGradientPanel1.add(jLabel14);
        jLabel14.setBounds(90, 50, 130, 30);

        jlbTime.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jlbTime.setForeground(new java.awt.Color(255, 255, 255));
        jlbTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTime.setText("Timer");
        kGradientPanel1.add(jlbTime);
        jlbTime.setBounds(0, 660, 240, 40);

        jlbLichChieu.setBackground(new java.awt.Color(0, 102, 102));
        jlbLichChieu.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jlbLichChieu.setForeground(new java.awt.Color(51, 51, 51));
        jlbLichChieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinema/image/planner.png"))); // NOI18N
        jlbLichChieu.setText("BÁN VÉ");
        jlbLichChieu.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jlbLichChieu.setOpaque(true);
        kGradientPanel1.add(jlbLichChieu);
        jlbLichChieu.setBounds(0, 110, 240, 60);

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseExited
        jlbClose.setBackground(new Color(0, 102, 102));
        jlbClose.setOpaque(true);
    }//GEN-LAST:event_jlbCloseMouseExited

    private void jlbCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseEntered
        jlbClose.setBackground(new Color(204, 204, 204));
        jlbClose.setOpaque(true);
    }//GEN-LAST:event_jlbCloseMouseEntered

    private void jlbCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jlbCloseMouseClicked

    private void jlbExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbExit1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlbExit1MouseClicked

    private void jlbExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbExit1MouseEntered
        jlbExit1.setBackground(new Color(204, 204, 204));
        jlbExit1.setOpaque(true);
    }//GEN-LAST:event_jlbExit1MouseEntered

    private void jlbExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbExit1MouseExited
        jlbExit1.setBackground(new Color(0, 102, 102));
        jlbExit1.setOpaque(true);
    }//GEN-LAST:event_jlbExit1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        QuestionDialog qd = new QuestionDialog(this, rootPaneCheckingEnabled);
        qd.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jlbAvatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAvatarMouseClicked

    }//GEN-LAST:event_jlbAvatarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreenStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreenStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreenStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreenStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreenStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jlbAvatar;
    private javax.swing.JLabel jlbClose;
    private javax.swing.JLabel jlbExit1;
    private javax.swing.JLabel jlbLichChieu;
    private javax.swing.JLabel jlbTime;
    private javax.swing.JPanel jpnQuanLyPhim;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblHinh;
    // End of variables declaration//GEN-END:variables
}
