/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

import com.cinema.controll.PhimControllInsert;
import com.cinema.controll.PhimControllUpdate;
import com.cinema.controll.PhimControllView;
import com.cinema.dao.LoaiPhimDAO;
import com.cinema.dao.PhimDAO;
import com.cinema.dialog.IPopupDialog;
import com.cinema.model.Phim;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thanh
 */
public class QuanLyPhim extends javax.swing.JPanel {

    private static final String DETAIL = "Chi Tiết";
    private static final String UPDATE = "Cập Nhật";
    private static final String FONT_NAME = "Tohama";
    JPopupMenu popupMenu = new JPopupMenu();
    PhimDAO dao = new PhimDAO();
    LoaiPhimDAO lpDao = new LoaiPhimDAO();
    List<Phim> list = new ArrayList<>();
    
    
    
    public QuanLyPhim() {
        initComponents();        
        addPopupView();
        this.fillToTable();
    }

    private void addPopupView() {
        PhimControllView avtDialog = new PhimControllView(null, true, tblView, this);
        PhimControllUpdate pUpdate = new PhimControllUpdate(null, true, tblView, this);
        
        
        JMenuItem avtItem = new JMenuItem(DETAIL, new ImageIcon("src/com/cinema/image/user.png"));
        avtItem.setFont(new Font(FONT_NAME, Font.PLAIN, 15));
        avtItem.setCursor(new Cursor(Cursor.HAND_CURSOR));
        avtItem.addActionListener(new InsertRowsActionAdapter(avtDialog));
        popupMenu.add(avtItem);
        
        
        JMenuItem uptItem = new JMenuItem(UPDATE, new ImageIcon("src/com/cinema/image/refresh.png"));
        uptItem.setFont(new Font(FONT_NAME, Font.PLAIN, 15));
        uptItem.setCursor(new Cursor(Cursor.HAND_CURSOR));
        uptItem.addActionListener(new InsertRowsActionAdapter(pUpdate));
        popupMenu.add(uptItem);
        
        
        tblView.setComponentPopupMenu(popupMenu);
        tblView.addMouseListener(new PopupListener());

    }

    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        model.setRowCount(0);
        try {
            list = dao.select();
            for (Phim pm : list) {
                Object[] row = {
                    pm.getMaPhim(),
                    pm.getTenPhim(),
                    pm.getNhaSanXuat(),
                    pm.getDoTuoi() == 1 ? "Mọi độ tuổi" : pm.getDoTuoi(),
                    pm.getThoiLuong(),
                    pm.getNgayCongChieu(),
                    lpDao.findByID(pm.getMaLoaiPhim())
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void Search(String text) {
        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        model.setRowCount(0);
        try {
            for (Phim pm : list) {
                if (pm.getTenPhim().contains(text)) {
                    Object[] row = new Object[]{
                        pm.getMaPhim(),
                        pm.getTenPhim(),
                        pm.getNhaSanXuat(),
                        pm.getDoTuoi(),
                        pm.getThoiLuong(),
                        pm.getNgayCongChieu(),
                        pm.getPoster()
                    };
                    model.addRow(row);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1290, 770));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinema/image/searchIcon.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        tblView.setBackground(new java.awt.Color(0, 102, 102));
        tblView.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tblView.setForeground(new java.awt.Color(255, 255, 255));
        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ PHIM", "TÊN PHIM", "NHÀ SẢN XUẤT", "ĐỘ TUỔI", "THỜI LƯỢNG (Phút)", "NGÀY CÔNG CHIẾU", "Thể Loại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblView.setRowHeight(37);
        tblView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblView);
        tblView.getAccessibleContext().setAccessibleDescription("");

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel2.setText("(Name of movie)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(790, 790, 790)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        this.Search(txtSearch.getText());
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        PhimControllInsert pi = new PhimControllInsert(null, true);
        pi.setJpanel(this);
        pi.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tblViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewMouseClicked
        
    }//GEN-LAST:event_tblViewMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    class PopupListener extends MouseAdapter {      
        
        @Override
        public void mousePressed(MouseEvent e) {
            showPopup(e);
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            showPopup(e);            
        }

        private void showPopup(MouseEvent e) {
            int r = tblView.rowAtPoint(e.getPoint());
            if (r >= 0 && r < tblView.getRowCount()) {
                tblView.setRowSelectionInterval(r, r);
            } else {
                tblView.clearSelection();
            }
            int rowindex = tblView.getSelectedRow();
            if (rowindex < 0) {
                return;
            }
            if (e.isPopupTrigger() && e.getComponent() instanceof JTable) {
                popupMenu.show(e.getComponent(), e.getX(), e.getY());
            }
        }
    }
}

class InsertRowsActionAdapter<T extends IPopupDialog> implements ActionListener {

    T dialog;

    InsertRowsActionAdapter(T adaptee) {
        this.dialog = adaptee;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        dialog.actionAfterClick(e);
    }
}
