/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

import com.cinema.controll.LichChieuControllInsert;
import com.cinema.controll.LichChieuControllUpdate;
import com.cinema.controll.LichChieuControllView;
import com.cinema.dao.LichChieuDAO;
import com.cinema.model.LichChieu;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thanh
 */
public class QuanLyLichChieu extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyLichChieu
     */
    LichChieuDAO dao = new LichChieuDAO();
    List<LichChieu> list = new ArrayList<>();
    JPopupMenu popupMenu = new JPopupMenu();
    private static final String DETAIL = "Chi Tiết";
    private static final String UPDATE = "Cập Nhật";
    private static final String FONT_NAME = "Tohama";

    public QuanLyLichChieu() {
        initComponents();
        this.fillToTable();
        this.addPopupView();
    }

    private void addPopupView() {
        LichChieuControllView avtDialog = new LichChieuControllView(null, true, tblView, this);
        LichChieuControllUpdate lcUpdate = new LichChieuControllUpdate(null, true, tblView, this);
        try {
            JMenuItem avtItem = new JMenuItem(DETAIL, new ImageIcon("src/com/cinema/image/user.png"));
            avtItem.setFont(new Font(FONT_NAME, Font.PLAIN, 15));
            avtItem.setCursor(new Cursor(Cursor.HAND_CURSOR));
            avtItem.addActionListener(new InsertRowsActionAdapter(avtDialog));
            popupMenu.add(avtItem);

            JMenuItem upDate = new JMenuItem(UPDATE, new ImageIcon("src/com/cinema/image/refresh.png"));
            upDate.setFont(new Font(FONT_NAME, Font.PLAIN, 15));
            upDate.setCursor(new Cursor(Cursor.HAND_CURSOR));
            upDate.addActionListener(new InsertRowsActionAdapter(lcUpdate));
            popupMenu.add(upDate);
        } catch (Exception e) {
            System.out.println("PopupMenu");
        }

        tblView.setComponentPopupMenu(popupMenu);
        tblView.addMouseListener(new PopupListener());

    }

    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        model.setRowCount(0);
        try {
            list = dao.select();
            for (LichChieu lc : list) {
                Object[] row
                        = {
                            lc.getMaLichChieu(),
                            lc.getNgayChieu(),
                            lc.getGioChieu(),
                            lc.getMaPhim(),
                            lc.getMaPhongChieu()};
                model.addRow(row);
            }
        } catch (Exception e) {
            System.out.println("1");
        }
    }

    private void search(String a) {
        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        model.setRowCount(0);
        try {
            for (LichChieu lc : list) {
                if (lc.getNgayChieu().contains(a)) {
                    Object[] row = new Object[]{
                        lc.getMaLichChieu(),
                        lc.getNgayChieu(),
                        lc.getGioChieu(),
                        lc.getMaPhim(),
                        lc.getMaPhongChieu()
                    };
                    model.addRow(row);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1290, 770));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        tblView.setBackground(new java.awt.Color(0, 102, 102));
        tblView.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tblView.setForeground(new java.awt.Color(255, 255, 255));
        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ LỊCH CHIẾU", "NGÀY CHIẾU", "GIỜ CHIẾU", "MÃ PHIM", "MÃ PHÒNG CHIẾU"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblView.setRowHeight(37);
        tblView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblView);

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinema/image/searchIcon.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel3.setText("(yyyy-mm--dd)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(810, 810, 810)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        this.search(txtSearch.getText());
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tblViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblViewMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        LichChieuControllInsert lcInsert = new LichChieuControllInsert(null, true);
        lcInsert.setJpanel(this);
        lcInsert.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    class PopupListener extends MouseAdapter {

        @Override
        public void mousePressed(MouseEvent e) {
            showPopup(e);
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            showPopup(e);
        }

        private void showPopup(MouseEvent e) {
            int r = tblView.rowAtPoint(e.getPoint());
            if (r >= 0 && r < tblView.getRowCount()) {
                tblView.setRowSelectionInterval(r, r);
            } else {
                tblView.clearSelection();
            }
            int rowindex = tblView.getSelectedRow();
            if (rowindex < 0) {
                return;
            }
            if (e.isPopupTrigger() && e.getComponent() instanceof JTable) {
                popupMenu.show(e.getComponent(), e.getX(), e.getY());
            }
        }
    }
}
