/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;


import com.cinema.controll.NhanVienControllInsert;
import com.cinema.controll.NhanVienControllUpdate;
import com.cinema.controll.NhanVienControllView;
import com.cinema.dao.TaiKhoanDAO;
import com.cinema.model.TaiKhoan;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thanh
 */
public class QuanLyNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyNhanVien
     */
    TaiKhoanDAO dao = new TaiKhoanDAO();
    List<TaiKhoan> list = new ArrayList<>();
    private static final String DETAIL = "Chi Tiết";
    private static final String UPDATE = "Cập Nhật";
    private static final String FONT_NAME = "Tohama";
    JPopupMenu popupMenu = new JPopupMenu();
    
    public QuanLyNhanVien() {
        initComponents();
        this.addPopupView();
        this.fillToTable();
    }
    
    private void addPopupView() {
        NhanVienControllView avtDialog = new NhanVienControllView(null, true, tblView, this);
        NhanVienControllUpdate nvUpdate = new NhanVienControllUpdate(null, true, tblView, this);
        
        
        JMenuItem avtItem = new JMenuItem(DETAIL, new ImageIcon("src/com/cinema/image/user.png"));
        avtItem.setFont(new Font(FONT_NAME, Font.PLAIN, 15));
        avtItem.setCursor(new Cursor(Cursor.HAND_CURSOR));
        avtItem.addActionListener(new InsertRowsActionAdapter(avtDialog));
        popupMenu.add(avtItem);
        
        
        JMenuItem uptItem = new JMenuItem(UPDATE, new ImageIcon("src/com/cinema/image/refresh.png"));
        uptItem.setFont(new Font(FONT_NAME, Font.PLAIN, 15));
        uptItem.setCursor(new Cursor(Cursor.HAND_CURSOR));
        uptItem.addActionListener(new InsertRowsActionAdapter(nvUpdate));
        popupMenu.add(uptItem);
        
        
        tblView.setComponentPopupMenu(popupMenu);
        tblView.addMouseListener(new PopupListener());

    }

    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        model.setRowCount(0);
        try {
            list = dao.findByRole();
            for (TaiKhoan tk : list) {
                Object row[] = {
                    tk.getTenDangNhap(),
                    tk.getHoTen(),
                    tk.isGioiTinh() == true ? "Nam" : "Nữ",
                    tk.getSDT(),
                    tk.getEmail()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void Search(String text) {
        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        model.setRowCount(0);
        try {
            for (TaiKhoan tk : list) {
                if (tk.getHoTen().contains(text)) {
                    Object[] row = new Object[]{
                        tk.getTenDangNhap(),
                        tk.getHoTen(),
                        tk.isGioiTinh(),
                        tk.getSDT(),
                        tk.getEmail()
                    };
                    model.addRow(row);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1290, 770));

        tblView.setBackground(new java.awt.Color(0, 102, 102));
        tblView.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tblView.setForeground(new java.awt.Color(255, 255, 255));
        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TÊN ĐĂNG NHẬP", "HỌ TÊN", "GIỚI TÍNH", "SỐ ĐIỆN THOẠI", "EMAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblView.setRowHeight(37);
        jScrollPane1.setViewportView(tblView);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinema/image/searchIcon.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel5.setText("(Name)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(840, 840, 840)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        this.Search(txtSearch.getText());
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        NhanVienControllInsert nvInsert = new NhanVienControllInsert(null, true);
        nvInsert.setJpanel(this);
        nvInsert.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
    class PopupListener extends MouseAdapter {      
        
        @Override
        public void mousePressed(MouseEvent e) {
            showPopup(e);
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            showPopup(e);            
        }

        private void showPopup(MouseEvent e) {
            int r = tblView.rowAtPoint(e.getPoint());
            if (r >= 0 && r < tblView.getRowCount()) {
                tblView.setRowSelectionInterval(r, r);
            } else {
                tblView.clearSelection();
            }
            int rowindex = tblView.getSelectedRow();
            if (rowindex < 0) {
                return;
            }
            if (e.isPopupTrigger() && e.getComponent() instanceof JTable) {
                popupMenu.show(e.getComponent(), e.getX(), e.getY());
            }
        }
    }
}
