/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java2_buoi5;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thanh
 */
public class lab3_buoi5 extends javax.swing.JFrame {

    
    public lab3_buoi5() {
        initComponents(); 
        setLocationRelativeTo(null);
    }
        ArrayList<SinhVien> list = new ArrayList<SinhVien>();
        
        
    public void addSinhVien(){
        SinhVien a = new SinhVien();
        a.hoTen = txthoten.getText();
        a.diem = Double.parseDouble(txtdiem.getText());
        a.hocluc = (String) cbbnganh.getSelectedItem();
        list.add(a);
        
        txthocluc.setText(a.getGrade());
        chkphanthuong.setSelected(a.isBonus());
        
    }
    public void removeSinhVien() {
        try {
            int index = tabledulieu.getSelectedRow();
            list.remove(index);
        } catch (ArrayIndexOutOfBoundsException a) {
            JOptionPane.showMessageDialog(this, "Hãy chọn sinh viên!");
        }
    }
    
    public void updateSinhVien() {
        int index = tabledulieu.getSelectedRow();
        SinhVien sv = list.get(index);
        sv.hoTen = txthoten.getText();
        sv.diem = Double.parseDouble(txtdiem.getText());
        sv.hocluc = (String) cbbnganh.getSelectedItem();
        txthocluc.setText(sv.getGrade());
        chkphanthuong.setSelected(sv.isBonus());
    }
    
     public void fillToTable() {
        DefaultTableModel mode = (DefaultTableModel) tabledulieu.getModel();
        mode.setRowCount(0);
        for (SinhVien i : list) {
            Object[] row = new Object[]{
                i.hoTen, i.diem, i.hocluc,i.getGrade(), i.isBonus()
            };
            mode.addRow(row);
        }

    }
     
      
    

    public void showDetail() {
        
            
        int index = tabledulieu.getSelectedRow();
        SinhVien sv = list.get(index);
        sv.hoTen = txthoten.getText();
        sv.diem = Double.parseDouble(txtdiem.getText());
        sv.hocluc = (String) cbbnganh.getSelectedItem();
        txthocluc.setText(sv.getGrade());
        chkphanthuong.setSelected(sv.isBonus());
    }
       
    public void orderByTen(){
        Comparator<SinhVien> com = new Comparator<SinhVien>(){

            @Override
            public int compare(SinhVien o1, SinhVien o2) {
                return o1.hoTen.compareTo(o2.hoTen);
            }
            
        };
        Collections.sort(list, com);
    }
    
    public void orderByDiem(){
        Comparator<SinhVien> com = new Comparator<SinhVien>(){

            @Override
            public int compare(SinhVien o1, SinhVien o2) {
                Double d1 = o1.diem;
                Double d2 = o2.diem;
                return d1.compareTo(d2);
            }
            
        };
        Collections.sort(list, com);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblsinhvien = new javax.swing.JLabel();
        lblhoten = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblnganh = new javax.swing.JLabel();
        lblhocluc = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        txtdiem = new javax.swing.JTextField();
        txthocluc = new javax.swing.JTextField();
        btthem = new javax.swing.JButton();
        lbxoa = new javax.swing.JButton();
        btcapnhat = new javax.swing.JButton();
        btnhapmoi = new javax.swing.JButton();
        chkphanthuong = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabledulieu = new javax.swing.JTable();
        cbbnganh = new javax.swing.JComboBox();
        jbtxapxepten = new javax.swing.JButton();
        jbtxapsepdiem = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("Quản Lý Sinh Viên"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        lblsinhvien.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lblsinhvien.setForeground(new java.awt.Color(255, 0, 51));
        lblsinhvien.setText("                     QUẢN LÝ SINH VIÊN");

        lblhoten.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblhoten.setText("HỌ VÀ TÊN");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("ĐIỂM");

        lblnganh.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblnganh.setText("NGÀNH");

        lblhocluc.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblhocluc.setText("HỌC LỰC");

        txtdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiemActionPerformed(evt);
            }
        });

        btthem.setText("THÊM");
        btthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemActionPerformed(evt);
            }
        });

        lbxoa.setText("XÓA");
        lbxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbxoaActionPerformed(evt);
            }
        });

        btcapnhat.setText("CẬP NHẬT");
        btcapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcapnhatActionPerformed(evt);
            }
        });

        btnhapmoi.setText("NHẬP MỚI");
        btnhapmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapmoiActionPerformed(evt);
            }
        });

        chkphanthuong.setText("CÓ PHẦN THƯỞNG");

        tabledulieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "HỌ VÀ TÊN", "ĐIỂM", "NGÀNH", "HỌC LỰC", "THƯỞNG"
            }
        ));
        tabledulieu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                tabledulieuAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabledulieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledulieuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabledulieu);

        cbbnganh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ứng dụng phần mềm", "Thiết kế đồ họa", "Nhà hàng khách sạn", "An ninh mạng", " " }));
        cbbnganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbnganhActionPerformed(evt);
            }
        });

        jbtxapxepten.setText("Sắp xếp theo tên");
        jbtxapxepten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtxapxeptenActionPerformed(evt);
            }
        });

        jbtxapsepdiem.setText("Sắp xếp theo điểm");
        jbtxapsepdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtxapsepdiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(lblsinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblnganh, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbbnganh, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblhoten, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txthoten))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtdiem))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblhocluc, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txthocluc)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkphanthuong)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btthem)
                                                .addGap(18, 18, 18)
                                                .addComponent(lbxoa)
                                                .addGap(18, 18, 18)
                                                .addComponent(btcapnhat)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnhapmoi)))
                                        .addGap(0, 204, Short.MAX_VALUE)))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jbtxapxepten)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtxapsepdiem, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblsinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblhoten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txthoten, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblnganh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbnganh, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txthocluc, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lblhocluc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(chkphanthuong)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btthem)
                    .addComponent(lbxoa)
                    .addComponent(btcapnhat)
                    .addComponent(btnhapmoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtxapxepten)
                    .addComponent(jbtxapsepdiem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbnganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbnganhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbnganhActionPerformed

    private void btthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemActionPerformed
        SinhVien sv = new SinhVien();
        sv.hoTen=txthoten.getText();
        sv.diem=Double.parseDouble(txtdiem.getText());
        txthocluc.setText(sv.getGrade());
        chkphanthuong.setSelected(sv.isBonus());
        this.addSinhVien();
        this.fillToTable();
        JOptionPane.showMessageDialog(this, "chúc mừng bạn đã thêm thành công");
    }//GEN-LAST:event_btthemActionPerformed

    private void btnhapmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapmoiActionPerformed
        txthoten.setText("");
        txtdiem.setText("");
        txthocluc.setText("");
        chkphanthuong.setSelected(false);
        txthoten.requestFocus();
    }//GEN-LAST:event_btnhapmoiActionPerformed

    private void txtdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiemActionPerformed

    private void btcapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcapnhatActionPerformed
        SinhVien sv = new SinhVien();
        sv.hoTen=txthoten.getText();
        sv.diem=Double.parseDouble(txtdiem.getText());
        txthocluc.setText(sv.getGrade());
        chkphanthuong.setSelected(sv.isBonus());
        this.updateSinhVien();
        this.fillToTable();
        JOptionPane.showMessageDialog(this, "chúc mừng bạn đã cập nhật thành công");
    }//GEN-LAST:event_btcapnhatActionPerformed

    private void tabledulieuAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabledulieuAncestorMoved
        
    }//GEN-LAST:event_tabledulieuAncestorMoved

    private void lbxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbxoaActionPerformed
        this.removeSinhVien();
        this.fillToTable();
    }//GEN-LAST:event_lbxoaActionPerformed

    private void tabledulieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledulieuMouseClicked
        
        // TODO add your handling code here:
        int index = tabledulieu.getSelectedRow();

        String hoten = list.get(index).getHoTen();
        txthoten.setText(hoten);
        
        String diem = String.valueOf(list.get(index).getDiem());
        txtdiem.setText(diem);

        String hocLuc = list.get(index).getHocluc();
        txthocluc.setText(hocLuc);

    }//GEN-LAST:event_tabledulieuMouseClicked

    private void jbtxapxeptenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtxapxeptenActionPerformed
        this.orderByTen();
        this.fillToTable();
    }//GEN-LAST:event_jbtxapxeptenActionPerformed

    private void jbtxapsepdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtxapsepdiemActionPerformed
        this.orderByDiem();
        this.fillToTable();
    }//GEN-LAST:event_jbtxapsepdiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lab3_buoi5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lab3_buoi5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lab3_buoi5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lab3_buoi5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lab3_buoi5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcapnhat;
    private javax.swing.JButton btnhapmoi;
    private javax.swing.JButton btthem;
    private javax.swing.JComboBox cbbnganh;
    private javax.swing.JCheckBox chkphanthuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtxapsepdiem;
    private javax.swing.JButton jbtxapxepten;
    private javax.swing.JLabel lblhocluc;
    private javax.swing.JLabel lblhoten;
    private javax.swing.JLabel lblnganh;
    private javax.swing.JLabel lblsinhvien;
    private javax.swing.JButton lbxoa;
    private javax.swing.JTable tabledulieu;
    private javax.swing.JTextField txtdiem;
    private javax.swing.JTextField txthocluc;
    private javax.swing.JTextField txthoten;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
