/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab_5;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author thanh
 */
public class bai2 extends javax.swing.JFrame {

    ArrayList<SinhVien> list = new ArrayList<SinhVien>();
        int current = 0;
        String user = "root";
        String pass = "";
        String url = "jdbc:mysql://localhost/SV";
        
    public bai2() {
        initComponents();
        LoadDataToArray();
        setLocationRelativeTo(null);
        Display(current);
    }
    
    public void Display(int i){
        SinhVien sv = list.get(i);
        txtdiachi.setText(sv.diaChi);
        txtemail.setText(sv.Email);
        txthovaten.setText(sv.hoTen);
        txtmasinhvien.setText(sv.Masv);
        txtsoDT.setText(sv.soDT);
        boolean gt = sv.gioiTinh;
        if(gt == true){
            rdonam.setSelected(true);
        }else{
            rdonu.setSelected(false);
        }
    }
    
    public void LoadDataToArray(){
        try {
            Connection con = DriverManager.getConnection(url, user,pass);
            Statement st = con.createStatement();
            String sql = "select * from sinhvien";
            ResultSet rs = st.executeQuery(sql);
            list.clear();
            while(rs.next()){
                String masv = rs.getString(1);
                String hoTen = rs.getString(2);
                String Email = rs.getString(3);
                String soDT = rs.getString(4);
                boolean gioiTinh = rs.getBoolean(5);
                String diaChi = rs.getString(6);
                SinhVien sv = new SinhVien(masv, hoTen, Email,soDT, diaChi, gioiTinh);
                list.add(sv);
            }
            con.close();
        } catch (Exception e) {
            System.out.println("Lỗi: "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtmasinhvien = new javax.swing.JTextField();
        txtsoDT = new javax.swing.JTextField();
        txthovaten = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        rdonam = new javax.swing.JRadioButton();
        rdonu = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdiachi = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);
        jPanel1.add(txtmasinhvien);
        txtmasinhvien.setBounds(140, 72, 210, 30);
        jPanel1.add(txtsoDT);
        txtsoDT.setBounds(140, 170, 210, 30);
        jPanel1.add(txthovaten);
        txthovaten.setBounds(140, 120, 210, 30);
        jPanel1.add(txtemail);
        txtemail.setBounds(140, 220, 210, 30);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(400, 70, 79, 30);

        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(401, 120, 75, 25);

        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(400, 170, 79, 25);

        jButton4.setText("SAVE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(400, 220, 80, 25);

        buttonGroup1.add(rdonam);
        rdonam.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        rdonam.setForeground(new java.awt.Color(255, 255, 255));
        rdonam.setText("Nam");
        jPanel1.add(rdonam);
        rdonam.setBounds(140, 270, 70, 29);

        buttonGroup1.add(rdonu);
        rdonu.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        rdonu.setForeground(new java.awt.Color(255, 255, 255));
        rdonu.setText("Nữ");
        rdonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdonuActionPerformed(evt);
            }
        });
        jPanel1.add(rdonu);
        rdonu.setBounds(220, 270, 70, 29);

        txtdiachi.setColumns(20);
        txtdiachi.setRows(5);
        jScrollPane1.setViewportView(txtdiachi);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 320, 340, 110);

        jButton5.setText("|<");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(230, 450, 47, 25);

        jButton6.setText("<<");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(290, 450, 51, 25);

        jButton7.setText(">>");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(360, 450, 51, 25);

        jButton8.setText(">|");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(430, 450, 47, 25);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(461, 0, 40, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Địa chỉ: ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 320, 90, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Giới Tính: ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 270, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email: ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 220, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Số ĐT: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 170, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Họ Và Tên:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 120, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã Sinh Viên: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 70, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quản lý User");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 10, 240, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\thanh\\Documents\\NetBeansProjects\\Java3\\src\\lab_5\\giphy2.gif")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdonuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdonuActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        jLabel9.setBackground(Color.DARK_GRAY);
        jLabel9.setOpaque(true);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jLabel9.setOpaque(false);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        current = list.size()-1;
        
        Display(current);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        current--;
        if(current < 0){
            JOptionPane.showMessageDialog(this, "Đang ở cuối");
            return;
        }
        Display(current);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        current++;
        if(current > list.size()-1){
            JOptionPane.showMessageDialog(this, "Đang ở đầu danh sách");
            return;
        }
        Display(current);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(txtmasinhvien.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Nhập mã sinh viên");
            txtmasinhvien.requestFocus();
            return;
        }try {
            Connection con = DriverManager.getConnection(url, user,pass);
            String sql="delete from sinhvien where maSV = ?";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, txtmasinhvien.getText());
            st.execute();
            JOptionPane.showMessageDialog(this, "Delete thành công");
            con.close();
            Display(current--);
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Error");
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtdiachi.setText("");
        txtemail.setText("");
        txthovaten.setText("");
        txtmasinhvien.setText("");
        txtsoDT.setText("");
        txtmasinhvien.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(txtmasinhvien.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Nhập mã sinh viên");
            txtmasinhvien.requestFocus();
            return;
        }
        try {
            Connection con = DriverManager.getConnection(url, user,pass);
            String sql = "update sinhvien set tenSV=?, Email=?, SDT=?, diaChi=?, gioiTinh=? where maSV=?";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, txthovaten.getText());
            st.setString(2, txtemail.getText());
            st.setString(3, txtsoDT.getText());
            st.setString(4, txtdiachi.getText());
            boolean gioiTinh;
            if(rdonam.isSelected()){
                gioiTinh = true;
            }else{
                gioiTinh = false;
            }
            st.setBoolean(5, gioiTinh);
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Update thành công!");
            con.close();
            LoadDataToArray();;
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Connection con = DriverManager.getConnection(url, user,pass);
            String sql = ("insert into sinhvien values(?,?,?,?,?,?)");
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, txtmasinhvien.getText());
            st.setString(2, txthovaten.getText());
            st.setString(3, txtemail.getText());
            st.setString(4, txtsoDT.getText());
            boolean gioiTinh;
            if(rdonam.isSelected()){
                gioiTinh = true;
            }else{
                gioiTinh = false;
                st.setBoolean(5, gioiTinh);
                st.setString(6, txtdiachi.getText());
                st.executeUpdate();
                JOptionPane.showMessageDialog(this, "Save thành công");
                con.close();
                LoadDataToArray();
            }
        } catch (Exception e) {
            System.out.println("Lỗi: " + e);
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        current = list.size()-1;
        
        
        Display(current);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdonam;
    private javax.swing.JRadioButton rdonu;
    private javax.swing.JTextArea txtdiachi;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txthovaten;
    private javax.swing.JTextField txtmasinhvien;
    private javax.swing.JTextField txtsoDT;
    // End of variables declaration//GEN-END:variables
}
