/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2;

/**
 *
 * @author thanh
 */
public class Bai_2 extends javax.swing.JFrame {

    /**
     * Creates new form Bai_2
     */
    public Bai_2() {
        initComponents();
        setLocationRelativeTo(this);
    }
    private long a = 0;
    private String phepToan="";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnso1 = new javax.swing.JButton();
        btnso2 = new javax.swing.JButton();
        btnso3 = new javax.swing.JButton();
        btnchia = new javax.swing.JButton();
        btnbinh = new javax.swing.JButton();
        btnso4 = new javax.swing.JButton();
        btnso5 = new javax.swing.JButton();
        btnso6 = new javax.swing.JButton();
        btnx = new javax.swing.JButton();
        btnphantram = new javax.swing.JButton();
        btnso7 = new javax.swing.JButton();
        btnso8 = new javax.swing.JButton();
        btnso9 = new javax.swing.JButton();
        btntru = new javax.swing.JButton();
        btnphantu = new javax.swing.JButton();
        btnso0 = new javax.swing.JButton();
        btnamduong = new javax.swing.JButton();
        btnc = new javax.swing.JButton();
        btncong = new javax.swing.JButton();
        btnketqua = new javax.swing.JButton();
        txtso = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        jButton9.setText("jButton9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel1.setText("CASIO");

        btnso1.setText("1");
        btnso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnso1ActionPerformed(evt);
            }
        });

        btnso2.setText("2");
        btnso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnso2ActionPerformed(evt);
            }
        });

        btnso3.setText("3");
        btnso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnso3ActionPerformed(evt);
            }
        });

        btnchia.setText("/");
        btnchia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchiaActionPerformed(evt);
            }
        });

        btnbinh.setText("sqrt");
        btnbinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbinhActionPerformed(evt);
            }
        });

        btnso4.setText("4");
        btnso4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnso4ActionPerformed(evt);
            }
        });

        btnso5.setText("5");
        btnso5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnso5ActionPerformed(evt);
            }
        });

        btnso6.setText("6");
        btnso6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnso6ActionPerformed(evt);
            }
        });

        btnx.setText("*");
        btnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxActionPerformed(evt);
            }
        });

        btnphantram.setText("%");

        btnso7.setText("7");
        btnso7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnso7ActionPerformed(evt);
            }
        });

        btnso8.setText("8");
        btnso8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnso8ActionPerformed(evt);
            }
        });

        btnso9.setText("9");
        btnso9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnso9ActionPerformed(evt);
            }
        });

        btntru.setText("-");
        btntru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntruActionPerformed(evt);
            }
        });

        btnphantu.setText("1/x");

        btnso0.setText("0");
        btnso0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnso0ActionPerformed(evt);
            }
        });

        btnamduong.setText("+/-");
        btnamduong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnamduongActionPerformed(evt);
            }
        });

        btnc.setText("C");

        btncong.setText("+");
        btncong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncongActionPerformed(evt);
            }
        });

        btnketqua.setText("=");
        btnketqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnketquaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnso1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                            .addComponent(btnso4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnso7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnso8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                            .addComponent(btnso5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnso2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnso0, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnamduong)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnc, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(btnso9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnso6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnso3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnchia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnbinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnx, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnphantram, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btntru, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btncong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnphantu, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                            .addComponent(btnketqua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(txtso, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnso1)
                    .addComponent(btnso2)
                    .addComponent(btnso3)
                    .addComponent(btnchia)
                    .addComponent(btnbinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnso4)
                    .addComponent(btnso5)
                    .addComponent(btnso6)
                    .addComponent(btnx)
                    .addComponent(btnphantram))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnso7)
                    .addComponent(btnso8)
                    .addComponent(btnso9)
                    .addComponent(btntru)
                    .addComponent(btnphantu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnso0)
                    .addComponent(btnamduong)
                    .addComponent(btnc)
                    .addComponent(btncong)
                    .addComponent(btnketqua))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbinhActionPerformed

    private void btnso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnso1ActionPerformed
        String gt = txtso.getText();
        if(gt.length()<12){
            if(gt.equals("0"))
                gt="";
            long so = Long.parseLong(gt + btnso1.getText());
            txtso.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnso1ActionPerformed

    private void btnso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnso2ActionPerformed
        String gt = txtso.getText();
        if(gt.length()<12){
            if(gt.equals("0"))
                gt="";
            long so = Long.parseLong(gt + btnso2.getText());
            txtso.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnso2ActionPerformed

    private void btnso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnso3ActionPerformed
       String gt = txtso.getText();
        if(gt.length()<12){
            if(gt.equals("0"))
                gt="";
            long so = Long.parseLong(gt + btnso3.getText());
            txtso.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnso3ActionPerformed

    private void btnso4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnso4ActionPerformed
        String gt = txtso.getText();
        if(gt.length()<12){
            if(gt.equals("0"))
                gt="";
            long so = Long.parseLong(gt + btnso4.getText());
            txtso.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnso4ActionPerformed

    private void btnso5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnso5ActionPerformed
        String gt = txtso.getText();
        if(gt.length()<12){
            if(gt.equals("0"))
                gt="";
            long so = Long.parseLong(gt + btnso5.getText());
            txtso.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnso5ActionPerformed

    private void btnso6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnso6ActionPerformed
        String gt = txtso.getText();
        if(gt.length()<12){
            if(gt.equals("0"))
                gt="";
            long so = Long.parseLong(gt + btnso6.getText());
            txtso.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnso6ActionPerformed

    private void btnso7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnso7ActionPerformed
        String gt = txtso.getText();
        if(gt.length()<12){
            if(gt.equals("0"))
                gt="";
            long so = Long.parseLong(gt + btnso7.getText());
            txtso.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnso7ActionPerformed

    private void btnso8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnso8ActionPerformed
        String gt = txtso.getText();
        if(gt.length()<12){
            if(gt.equals("0"))
                gt="";
            long so = Long.parseLong(gt + btnso8.getText());
            txtso.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnso8ActionPerformed

    private void btnso9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnso9ActionPerformed
        String gt = txtso.getText();
        if(gt.length()<12){
            if(gt.equals("0"))
                gt="";
            long so = Long.parseLong(gt + btnso9.getText());
            txtso.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnso9ActionPerformed

    private void btnso0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnso0ActionPerformed
        String gt = txtso.getText();
        if(gt.length()<12){
            if(gt.equals("0"))
                gt="";
            long so = Long.parseLong(gt + btnso0.getText());
            txtso.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnso0ActionPerformed

    private void btnamduongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnamduongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnamduongActionPerformed

    private void btnchiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchiaActionPerformed
        a=Long.parseLong(txtso.getText());
        if(a != 0){
            phepToan="/";
            txtso.setText("0");
        }
    }//GEN-LAST:event_btnchiaActionPerformed

    private void btnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxActionPerformed
        a=Long.parseLong(txtso.getText());
        if(a != 0){
            phepToan="*";
            txtso.setText("0");
        }
    }//GEN-LAST:event_btnxActionPerformed

    private void btntruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntruActionPerformed
        a=Long.parseLong(txtso.getText());
        phepToan = "-";
        txtso.setText("0");
    }//GEN-LAST:event_btntruActionPerformed

    private void btncongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncongActionPerformed
        a=Long.parseLong(txtso.getText());
        phepToan = "+";
        txtso.setText("0");
    }//GEN-LAST:event_btncongActionPerformed

    private void btnketquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnketquaActionPerformed
        long kq = 0;
        long b = Long.parseLong(txtso.getText());
        if(phepToan.length()>0){
            if(phepToan.equals("+")){
                kq = a + b;
                txtso.setText(String.valueOf(kq));
            }else if(phepToan.equals("-")){
                kq = a - b;
                txtso.setText(String.valueOf(kq));
            }else if(phepToan.equals("*")){
                kq = a * b; 
                txtso.setText(String.valueOf(kq));
            }else if(phepToan.equals("/")){
                kq = a / b;
                txtso.setText(String.valueOf(kq));
            }
            phepToan = "";
            a = 0;
        }
        
    }//GEN-LAST:event_btnketquaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnamduong;
    private javax.swing.JButton btnbinh;
    private javax.swing.JButton btnc;
    private javax.swing.JButton btnchia;
    private javax.swing.JButton btncong;
    private javax.swing.JButton btnketqua;
    private javax.swing.JButton btnphantram;
    private javax.swing.JButton btnphantu;
    private javax.swing.JButton btnso0;
    private javax.swing.JButton btnso1;
    private javax.swing.JButton btnso2;
    private javax.swing.JButton btnso3;
    private javax.swing.JButton btnso4;
    private javax.swing.JButton btnso5;
    private javax.swing.JButton btnso6;
    private javax.swing.JButton btnso7;
    private javax.swing.JButton btnso8;
    private javax.swing.JButton btnso9;
    private javax.swing.JButton btntru;
    private javax.swing.JButton btnx;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtso;
    // End of variables declaration//GEN-END:variables
}
