/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cinema.controll;

import cinema.QuanLyLichChieu;
import com.cinema.dao.LichChieuDAO;
import com.cinema.dao.PhimDAO;
import com.cinema.dao.PhongChieuDAO;
import com.cinema.dialog.IPopupDialog;
import com.cinema.helper.SonOptionPane;
import com.cinema.model.LichChieu;
import com.cinema.model.Phim;
import com.cinema.model.PhongChieu;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JTable;

/**
 *
 * @author thanh
 */
public class LichChieuControllUpdate extends javax.swing.JDialog implements IPopupDialog {

    /**
     * Creates new form LichChieuCotroll
     */
    private LichChieuDAO dao = new LichChieuDAO();
    private QuanLyLichChieu jpanel;
    private PhimDAO pdao = new PhimDAO();
    private PhongChieuDAO pcdao = new PhongChieuDAO();
    private JTable table;

    public LichChieuControllUpdate(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.setItemPhim();
        this.setItemPhongChieu();
    }

    public LichChieuControllUpdate(java.awt.Frame parent, boolean model, JTable table, QuanLyLichChieu jpanel) {
        super(parent, model);
        initComponents();
        this.table = table;
        this.jpanel = jpanel;
        setLocationRelativeTo(null);
        this.setItemPhim();
        this.setItemPhongChieu();
    }

    LichChieu getModel() {
        LichChieu lc = new LichChieu();
        lc.setMaLichChieu(Integer.valueOf(lblMaLichChieu.getText()));
        lc.setNgayChieu(txtNgayChieu.getText());
        lc.setGioChieu((String) cboGioChieu.getSelectedItem());
        lc.setMaPhim(((Phim) cboPhim.getSelectedItem()).getMaLoaiPhim());
        lc.setMaPhongChieu(((PhongChieu) cboPhongChieu.getSelectedItem()).getMaPhongChieu());
        return lc;
    }

    private void setItemPhim() {
        List<Phim> list = pdao.select();
        for (Phim pm : list) {
            cboPhim.addItem(pm);
        }
    }

    private void setItemPhongChieu() {
        List<PhongChieu> list = pcdao.select();
        for (PhongChieu pc : list) {
            cboPhongChieu.addItem(pc);
        }
    }

    private void update() {
        LichChieu lc = getModel();
        try {
            dao.update(lc);
            this.dispose();
            this.jpanel.fillToTable();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private boolean check() {
        boolean KiemTra = false;
        String ngayChieu = txtNgayChieu.getText();
        String regexDate = "\\d{4}-\\d{1,2}-\\d{1,2}";
        if (ngayChieu.isEmpty()) {
            SonOptionPane.showMessage(super.getParent(), "KHÔNG ĐƯỢC ĐỂ TRỐNG!", SonOptionPane.WARNING);
            txtNgayChieu.requestFocus();
            KiemTra = false;
        } else if (!ngayChieu.matches(regexDate)) {
            SonOptionPane.showMessage(super.getParent(), "VUI LÒNG NHẬP ĐÚNG ĐỊNH DẠNG!", SonOptionPane.INFO);
            txtNgayChieu.requestFocus();
            KiemTra = false;
        } else {
            KiemTra = true;
        }
        return KiemTra;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblMaLichChieu = new javax.swing.JLabel();
        cboPhongChieu = new javax.swing.JComboBox<PhongChieu>();
        cboGioChieu = new javax.swing.JComboBox<>();
        cboPhim = new javax.swing.JComboBox<Phim>();
        btnKhong1 = new keeptoo.KButton();
        btnKhong = new keeptoo.KButton();
        txtNgayChieu = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("MÃ LỊCH CHIẾU: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 153, 51)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("MÃ LỊCH CHIẾU: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("NGÀY CHIẾU: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("GIỜ CHIẾU: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("TÊN PHIM: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("MÃ PHÒNG");

        lblMaLichChieu.setBackground(new java.awt.Color(204, 204, 204));
        lblMaLichChieu.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        cboPhongChieu.setBorder(new javax.swing.border.MatteBorder(null));
        cboPhongChieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPhongChieuActionPerformed(evt);
            }
        });

        cboGioChieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "11:00", "13:30", "15:00", "17:30", "20:00", "22:30", " " }));
        cboGioChieu.setBorder(new javax.swing.border.MatteBorder(null));

        cboPhim.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        cboPhim.setBorder(new javax.swing.border.MatteBorder(null));
        cboPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPhimActionPerformed(evt);
            }
        });

        btnKhong1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnKhong1.setText("THOÁT");
        btnKhong1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnKhong1.setkBackGroundColor(new java.awt.Color(153, 153, 153));
        btnKhong1.setkEndColor(new java.awt.Color(102, 102, 102));
        btnKhong1.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        btnKhong1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnKhong1.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        btnKhong1.setkSelectedColor(new java.awt.Color(102, 102, 102));
        btnKhong1.setkStartColor(new java.awt.Color(204, 204, 204));
        btnKhong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhong1ActionPerformed(evt);
            }
        });

        btnKhong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnKhong.setText("CẬP NHẬT");
        btnKhong.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnKhong.setkBackGroundColor(new java.awt.Color(153, 153, 153));
        btnKhong.setkEndColor(new java.awt.Color(102, 102, 102));
        btnKhong.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        btnKhong.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnKhong.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        btnKhong.setkSelectedColor(new java.awt.Color(102, 102, 102));
        btnKhong.setkStartColor(new java.awt.Color(204, 204, 204));
        btnKhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhongActionPerformed(evt);
            }
        });

        txtNgayChieu.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboGioChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMaLichChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNgayChieu)
                                .addGap(2, 2, 2))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnKhong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboPhongChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaLichChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(txtNgayChieu))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboGioChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboPhongChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKhong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKhong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhong1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnKhong1ActionPerformed

    private void btnKhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhongActionPerformed
        if(this.check()){
            this.update();
        }
    }//GEN-LAST:event_btnKhongActionPerformed

    private void cboPhongChieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPhongChieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPhongChieuActionPerformed

    private void cboPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPhimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPhimActionPerformed

    public QuanLyLichChieu getJpanel() {
        return jpanel;
    }

    public void setJpanel(QuanLyLichChieu jpanel) {
        this.jpanel = jpanel;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LichChieuControllUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LichChieuControllUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LichChieuControllUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LichChieuControllUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LichChieuControllUpdate dialog = new LichChieuControllUpdate(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnKhong;
    private keeptoo.KButton btnKhong1;
    private javax.swing.JComboBox<String> cboGioChieu;
    private javax.swing.JComboBox<Phim> cboPhim;
    private javax.swing.JComboBox<PhongChieu> cboPhongChieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMaLichChieu;
    private javax.swing.JTextField txtNgayChieu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionAfterClick(ActionEvent e) {
        int row = table.getSelectedRow();
        int idLc = (int) table.getValueAt(row, 0);
        LichChieuDAO dao = new LichChieuDAO();
        LichChieu lc = dao.findByID(idLc);
        lblMaLichChieu.setText(String.valueOf(lc.getMaLichChieu()));
        txtNgayChieu.setText(lc.getNgayChieu());
        cboGioChieu.setSelectedItem(lc.getGioChieu());
        cboPhim.setSelectedItem(((Phim) cboPhim.getSelectedItem()).getMaPhim());
        cboPhongChieu.setSelectedItem(((PhongChieu) cboPhongChieu.getSelectedItem()).getMaPhongChieu());
        this.setVisible(true);
    }

}
