/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cinema.controll;

import cinema.QuanLyPhim;
import com.cinema.dao.LoaiPhimDAO;
import com.cinema.dao.PhimDAO;
import com.cinema.dialog.IPopupDialog;
import com.cinema.helper.SonOptionPane;
import com.cinema.model.LoaiPhim;
import com.cinema.model.Phim;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JTable;

/**
 *
 * @author thanh
 */
public class PhimControllView extends javax.swing.JDialog implements IPopupDialog {

    private PhimDAO dao = new PhimDAO();
    private LoaiPhimDAO lpDao = new LoaiPhimDAO();
    private QuanLyPhim jpanel;
    private JTable table;

    public PhimControllView(java.awt.Frame parent, boolean model) {
        super(parent, model);
        initComponents();
        setLocationRelativeTo(null);
        this.SetLabelLoaiPhim();
    }

    public PhimControllView(java.awt.Frame parent, boolean model, JTable table, QuanLyPhim jpanel) {
        super(parent, model);
        initComponents();
        this.table = table;
        this.jpanel = jpanel;
        this.SetLabelLoaiPhim();
        setLocationRelativeTo(null);
    }
    
    private void SetLabelLoaiPhim(){
        List<LoaiPhim> list = lpDao.fillAll();
        for(LoaiPhim lp : list){
            lblTheLoai.setText(String.valueOf(lp));
        }
    }
    
    public void delete() {
        try {
            String MaPhim = lblMaPhim.getText();
            dao.delete(MaPhim);
            this.dispose();
            this.jpanel.fillToTable();
        } catch (Exception e) {
            SonOptionPane.showMessage(super.getParent(), "PHIM NÀY ĐÃ ĐƯỢC CÔNG CHIẾU!", SonOptionPane.WARNING);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblHinh = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnKhong1 = new keeptoo.KButton();
        jLabel8 = new javax.swing.JLabel();
        lblTheLoai = new javax.swing.JLabel();
        lblMaPhim = new javax.swing.JLabel();
        lblNhaSanXuat = new javax.swing.JLabel();
        lblDoTuoi = new javax.swing.JLabel();
        lblThoiLuong = new javax.swing.JLabel();
        lblNgayCongChieu = new javax.swing.JLabel();
        lblTenPhim = new javax.swing.JLabel();
        kButton1 = new keeptoo.KButton();
        jPanel3 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 204, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHinh.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
        });
        jPanel1.add(lblHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, 249));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nhà sản xuất: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 118, 160, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Thể loại: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 330, 160, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Tên Phim: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 65, 160, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Độ tuổi: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 171, 160, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Thời lượng: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 224, 160, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Ngày công chiếu: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 277, 160, 40));

        btnKhong1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnKhong1.setText("THOÁT");
        btnKhong1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnKhong1.setkBackGroundColor(new java.awt.Color(153, 153, 153));
        btnKhong1.setkEndColor(new java.awt.Color(102, 102, 102));
        btnKhong1.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        btnKhong1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnKhong1.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        btnKhong1.setkSelectedColor(new java.awt.Color(153, 153, 153));
        btnKhong1.setkStartColor(new java.awt.Color(204, 204, 204));
        btnKhong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhong1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnKhong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 240, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Mã: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 18, 170, 40));

        lblTheLoai.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTheLoai.setPreferredSize(new java.awt.Dimension(40, 250));
        jPanel1.add(lblTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 330, 250, 40));

        lblMaPhim.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblMaPhim.setForeground(new java.awt.Color(255, 0, 0));
        lblMaPhim.setText("123");
        lblMaPhim.setPreferredSize(new java.awt.Dimension(40, 250));
        jPanel1.add(lblMaPhim, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 18, 250, 40));

        lblNhaSanXuat.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        lblNhaSanXuat.setText("123");
        lblNhaSanXuat.setPreferredSize(new java.awt.Dimension(40, 250));
        jPanel1.add(lblNhaSanXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 118, 250, 40));

        lblDoTuoi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblDoTuoi.setText("321");
        lblDoTuoi.setPreferredSize(new java.awt.Dimension(40, 250));
        jPanel1.add(lblDoTuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 171, 250, 40));

        lblThoiLuong.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblThoiLuong.setText("321");
        lblThoiLuong.setPreferredSize(new java.awt.Dimension(40, 250));
        jPanel1.add(lblThoiLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 224, 250, 40));

        lblNgayCongChieu.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        lblNgayCongChieu.setForeground(new java.awt.Color(0, 51, 153));
        lblNgayCongChieu.setText("123");
        lblNgayCongChieu.setPreferredSize(new java.awt.Dimension(40, 250));
        jPanel1.add(lblNgayCongChieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 277, 250, 40));

        lblTenPhim.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTenPhim.setForeground(new java.awt.Color(255, 0, 0));
        lblTenPhim.setText("123");
        lblTenPhim.setPreferredSize(new java.awt.Dimension(40, 250));
        jPanel1.add(lblTenPhim, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 65, 250, 40));

        kButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1)));
        kButton1.setText("XÓA");
        kButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(153, 153, 153));
        kButton1.setkEndColor(new java.awt.Color(102, 102, 102));
        kButton1.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        kButton1.setkSelectedColor(new java.awt.Color(204, 204, 204));
        kButton1.setkStartColor(new java.awt.Color(204, 204, 204));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 400, 260, -1));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 420, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKhong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhong1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnKhong1ActionPerformed

    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked
        // TODO add your handling code here:B 
    }//GEN-LAST:event_lblHinhMouseClicked

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        this.delete();
    }//GEN-LAST:event_kButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhimControllView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhimControllView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhimControllView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhimControllView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PhimControllView dialog = new PhimControllView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnKhong1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private keeptoo.KButton kButton1;
    private javax.swing.JLabel lblDoTuoi;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblMaPhim;
    private javax.swing.JLabel lblNgayCongChieu;
    private javax.swing.JLabel lblNhaSanXuat;
    private javax.swing.JLabel lblTenPhim;
    private javax.swing.JLabel lblTheLoai;
    private javax.swing.JLabel lblThoiLuong;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionAfterClick(ActionEvent e) {
        int row = table.getSelectedRow();
        int idPhim = (int) table.getValueAt(row, 0);
        PhimDAO phimDAO = new PhimDAO();
        Phim phim = phimDAO.findByID(idPhim);
        lblMaPhim.setText(String.valueOf(phim.getMaPhim()));
        lblTenPhim.setText(phim.getTenPhim());
        lblNhaSanXuat.setText(phim.getNhaSanXuat());
        lblDoTuoi.setText(String.valueOf(phim.getDoTuoi()));
        lblThoiLuong.setText(String.valueOf(phim.getNgayCongChieu()));
        lblNgayCongChieu.setText(phim.getNgayCongChieu());
        lblTheLoai.setText(String.valueOf(phim.getMaLoaiPhim()));
        if (phim.getPoster() != null) {
            lblHinh.setIcon(new ImageIcon(new ImageIcon("src\\com\\cinema\\avatar\\" + phim.getPoster()).getImage().getScaledInstance(lblHinh.getWidth(), lblHinh.getHeight(), Image.SCALE_SMOOTH)));
        }
        this.setVisible(true);
    }
}
